<?php
$homeCategories = $this->getMenuCategories();
?>

<div class="menu">
	<div class="menu-content-wrapper">
		<div class="title">
			<span>Collections</span>
			<span>Eshop</span>
		</div>

		<div class="image-wrapper">
			<img class="img-menu" src="<?php echo $this->getSkinUrl('images/media/default.jpg') ?>" />
		</div>

		<div class="onglets">
			<ul>
				<li>À propos</li>
				<li>Blog</li>
				<li>Contact</li>
				<li>Connexion</li>
				<li>Mention légales</li>
			</ul>
		</div>

		<div class="collections">
			<ul>
				<?php if (is_array($homeCategories) && count($homeCategories)) { ?>
					<?php foreach($homeCategories as $_category) { 
		  			?>
						<li class="collection">
							<a class="collection-link" href="<?php echo $_category['url'] ?>" onmouseover="hover(this, '<?php echo $_category['menu_image'] ?>');" onmouseout="unhover(this);">
								<span class="main"><?php echo $_category['name'] ?>, </span>
								<span class="sub"><?php echo $_category['parent_category']->getName() ?></span>
							</a>
						</li>
						<br>
					<?php } ?>
				<?php } ?>
				<li><a href="#">Voir tout</a></li>
			</ul>
		</div>
	</div>
</div>

<script type="text/javascript">
	function hover(element, subcategory) {
    	document.querySelector('.img-menu').setAttribute('src', '/media/catalog/category/' + subcategory);
	}

	function unhover(element) {
    	document.querySelector('.img-menu').setAttribute('src', '/skin/frontend/rwd/argentin/images/media/default.jpg');
	}
</script>