<div class="menu">
	<div class="menu-content-wrapper">
		<div class="title">
			<span>Collections</span>
			<span>Eshop</span>
		</div>

		<div class="image-wrapper">
			<img src="<?php echo $this->getSkinUrl('images/media/default.jpg') ?>" />
		</div>

		<div class="onglets">
			<ul>
				<li>À propos</li>
				<li>Blog</li>
				<li>Contact</li>
				<li>Connexion</li>
				<li>Mention légales</li>
			</ul>
		</div>

		<div class="collections">
			<ul>
				<li class="collection">
					<span class="main">Automne-Hiver,</span>
					<span class="sub">2017, 2018, Sessùn</span>
				</li>
				<br>
				<li class="collection">
					<span class="main">Oui,</span>
					<span class="sub">Sessùn</span>
				</li>
				<br>
				<li class="collection">
					<span class="main">Silkani,</span>
					<span class="sub">Silkani</span>
				</li>
				<br>
				<li>Voir tout</li>
			</ul>
		</div>
	</div>
</div>